/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/professor/Header.vue')['default']
    Headers: typeof import('./src/components/professor/Headers.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Inicio: typeof import('./src/components/professor/Inicio.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    NewsCard: typeof import('./src/components/professor/NewsCard.vue')['default']
    ProfessorDashboard: typeof import('./src/components/professor/ProfessorDashboard.vue')['default']
    ProfessorMenu: typeof import('./src/components/professor/ProfessorMenu.vue')['default']
    ProjectsCard: typeof import('./src/components/professor/ProjectsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/professor/SidebarMenu.vue')['default']
  }
}
