/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Headers: typeof import('./src/components/professor/Headers.vue')['default']
    Inicio: typeof import('./src/components/professor/Inicio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/professor/SidebarMenu.vue')['default']
  }
}
